version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: server
    depends_on:
      - dev_db
  dev_db:
    image: postgres:15.0
    container_name: dev_db
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev_db
    ports:
      - '3500:5432'
    volumes:
      - postgresDB_dev:/var/lib/postgresql/data

  test-db:
    image: postgres:15.0
    container_name: test-DB
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=test
      - POSTGRES_DB=test_DB
    ports:
      - '3501:5432'
    volumes:
      - postgresDB_test:/var/lib/postgresql/data



volumes:
  postgresDB_dev:
  postgresDB_test: