version: '3.1'

services:
  dev_db:
    image: postgres:15.0
    container_name: dev_database
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev_db
    ports:
      - '4500:5432'
    volumes:
      - postgresDB_dev:/var/lib/postgresql/data

  test_db:
    image: postgres:15.0
    container_name: test_database
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test_db
    ports:
      - '4501:5432'
    volumes:
      - postgresDB_test:/var/lib/postgresql/data



volumes:
  postgresDB_dev:
  postgresDB_test: