version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: server
    depends_on:
      - dev_db
  dev_db:
    image: postgres:15.0
    container_name: dev_db
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev_db
    ports:
      - '4500:5432'
    volumes:
      - postgresDB_dev:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '8025:8025'
      - '1025:1025'

  # test_db:
  #   image: postgres:15.0
  #   container_name: test_db
  #   environment:
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_USER=test
  #     - POSTGRES_DB=test_db
  #   ports:
  #     - '4501:5432'
  #   volumes:
  #     - postgresDB_test:/var/lib/postgresql/data



volumes:
  postgresDB_dev:
  # postgresDB_test: